import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>Hello world</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Voluptatibus odio culpa inventore, asperiores est placeat explicabo
            officiis, suscipit delectus cupiditate, vero in tenetur dolorum
            totam non cum eveniet mollitia numquam. Esse natus quis nemo maxime
            placeat laborum, vitae neque fugit perferendis molestias dolores
            velit eveniet dignissimos reprehenderit. Reprehenderit, maiores
            reiciendis.
          </p>

          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos
            laborum, labore veniam vel saepe reiciendis voluptatum. Quibusdam
            vel quam officia.
          </p>

          <Link href="/ninjas">
            <a>See Ninja Listing</a>
          </Link>
        </div>
      </main>
    </div>
  );
}
